version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hexagonal-postgres
    ports:
      - "5430:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
